# Generated by Django 3.0.2 on 2020-01-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200114_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
